#!/bin/sh -e

if [ -z "$ANDROID_HOME" ]; then
    echo 'No $ANDROID_HOME specified.'
    exit 1
fi
if [ -z "$NDK" ]; then
    echo 'No $NDK specified.'
    exit 1
fi

VERSION=$1
PREV_VERSION=$2

git checkout refs/tags/release-$VERSION
git log --pretty=fuller --date=short refs/tags/release-$PREV_VERSION..HEAD > ChangeLog

autoreconf -i

./configure && \
    make dist-bzip2 && make dist-gzip && make dist-xz || echo "error"
make distclean

# mingw 32bit
export HOST=i686-w64-mingw32
export LABEL=win-32bit
./mingw-config
make -j8
./mingw-release
make distclean

# mingw 64bit
export HOST=x86_64-w64-mingw32
export LABEL=win-64bit
./mingw-config
make -j8
./mingw-release
make distclean

# android
./android-config
make -j8
./android-release
make distclean

# OSX builds are created separately using makerelease-osx.mk
