dnl  mpn_mul_1 - from x86_64/bd1 directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_mul_1)
define(__gmpn_mul_1, __gmpn_mul_1_bd1)
define(__gmpn_mul_1c,__gmpn_mul_1c_bd1)
define(__gmpn_preinv_mul_1,__gmpn_preinv_mul_1_bd1)
define(__gmpn_mul_1_cps,__gmpn_mul_1_cps_bd1)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_bd1)')

define(MUL_TOOM22_THRESHOLD,16)
define(MUL_TOOM33_THRESHOLD,57)
define(SQR_TOOM2_THRESHOLD,24)
define(SQR_TOOM3_THRESHOLD,139)
define(BMOD_1_TO_MOD_1_THRESHOLD,20)

include(../../gmp/mpn/x86_64/bd1/mul_1.asm)

