dnl  mpn_addmul_1 - from x86_64/coreisbr directory for fat binary.
dnl  Generated by configure - DO NOT EDIT.

define(OPERATION_addmul_1)
define(__gmpn_addmul_1, __gmpn_addmul_1_coreisbr)
define(__gmpn_addmul_1c,__gmpn_addmul_1c_coreisbr)
define(__gmpn_preinv_addmul_1,__gmpn_preinv_addmul_1_coreisbr)
define(__gmpn_addmul_1_cps,__gmpn_addmul_1_cps_coreisbr)

dnl  For k6 and k7 gcd_1 calling their corresponding mpn_modexact_1_odd
ifdef(`__gmpn_modexact_1_odd',,
`define(__gmpn_modexact_1_odd,__gmpn_modexact_1_odd_coreisbr)')

define(MUL_TOOM22_THRESHOLD,18)
define(MUL_TOOM33_THRESHOLD,57)
define(SQR_TOOM2_THRESHOLD,26)
define(SQR_TOOM3_THRESHOLD,81)
define(BMOD_1_TO_MOD_1_THRESHOLD,30)

include(../../gmp/mpn/x86_64/coreisbr/aorsmul_1.asm)

