/* mpn_mod_1 - from x86_64/fat directory for fat binary.
   Generated by configure - DO NOT EDIT. */

#define OPERATION_mod_1 1
#define __gmpn_mod_1           __gmpn_mod_1_fat
#define __gmpn_mod_1c          __gmpn_mod_1c_fat
#define __gmpn_preinv_mod_1  __gmpn_preinv_mod_1_fat
#define __gmpn_mod_1_cps     __gmpn_mod_1_cps_fat

#include "../../gmp/mpn/x86_64/fat/mod_1.c"

