.\"     Title: aria2c
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 01/28/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "ARIA2C" "1" "01/28/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
aria2c \- The high speed download utility
.SH "SYNOPSIS"
.sp
.RS 3n
.nf
aria2c [OPTIONS] URL ...
aria2c [OPTIONS] \-T TORRENT_FILE FILE ...
aria2c [OPTIONS] \-M METALINK_FILE
.fi
.RE
.SH "DESCRIPTION"
aria2 is a utility for downloading files. It has completely new design concept from its predecessor, Aria, and is written from scratch. aria2 has a segmented downloading engine in its core. It can download one file from multiple URLs or multiple connections from one URL. This results in very high speed downloading, much faster than ordinary browsers. This engine in was implemented in a single\-thread model. The architecture is clean and easy to extend. aria2 currently supports HTTP, FTP, and BitTorrent. It also supports Metalink version 3.0.
.sp
Please visit the project web site at http://aria2.sourceforge.net
.sp
.SH "OPTIONS"
.TP 3n
\-d, \-\-dir=DIR
The directory to store downloaded file.
.TP 3n
\-o, \-\-out=FILE
The file name for downloaded file.
.TP 3n
\-l, \-\-log=LOG
The file path to store log. If
\fI\-\fR
is specified, log is written to stdout.
.TP 3n
\-D, \-\-daemon
Run as daemon.
.TP 3n
\-s, \-\-split=N
Download a file using
\fIN\fR
connections.
\fIN\fR
must be between
\fI1\fR
and
\fI5\fR. This option affects all URLs. Thus, aria2 connects to each URL with
\fIN\fR
connections. Default:
\fI1\fR
.TP 3n
\-\-retry\-wait=SEC
Set amount of time in second between requests for errors. Specify a value between
\fI0\fR
and
\fI60\fR. Default:
\fI5\fR
.TP 3n
\-t, \-\-timeout=SEC
Set timeout in second. Default:
\fI60\fR
.TP 3n
\-m, \-\-max\-tries=N
Set number of tries.
\fI0\fR
means unlimited. Default:
\fI5\fR
.TP 3n
\-\-http\-proxy=HOST:PORT
Use HTTP proxy server. This affects to all URLs.
.TP 3n
\-\-http\-user=USER
Set HTTP user. This affects to all URLs.
.TP 3n
\-\-http\-passwd=PASSWD
Set HTTP password. This affects to all URLs.
.TP 3n
\-\-http\-proxy\-user=USER
Set HTTP proxy user. This affects to all URLs
.TP 3n
\-\-http\-proxy\-passwd=PASSWD
Set HTTP proxy password. This affects to all URLs.
.TP 3n
\-\-http\-proxy\-method=METHOD
Set the method to use in proxy request.
\fIMETHOD\fR
is either
\fIget\fR
or
\fItunnel\fR. Default:
\fItunnel\fR
.TP 3n
\-\-http\-auth\-scheme=SCHEME
Set HTTP authentication scheme. Currently,
\fIbasic\fR
is the only supported scheme. Default:
\fIbasic\fR
.TP 3n
\-\-referer=REFERER
Set Referer. This affects to all URLs.
.TP 3n
\-\-ftp\-user=USER
Set FTP user. This affects to all URLs. Default:
\fIanonymous\fR
.TP 3n
\-\-ftp\-passwd=PASSWD
Set FTP password. This affects to all URLs. Default:
\fIARIA2USER@\fR
.TP 3n
\-\-ftp\-type=TYPE
Set FTP transfer type. TYPE is either
\fIbinary\fR
or
\fIascii\fR. Default:
\fIbinary\fR
.TP 3n
\-p, \-\-ftp\-pasv
Use passive mode in FTP.
.TP 3n
\-\-ftp\-via\-http\-proxy=METHOD
Use HTTP proxy in
\fIFTP\fR.
\fIMETHOD\fR
is either
\fIget\fR
or
\fItunnel\fR. Default:
\fItunnel\fR
.TP 3n
\-\-lowest\-speed\-limit=SPEED
Close connection if download speed is lower than or equal to this value(bytes per sec). 0 means aria2 does not care lowest speed limit. You can append
\fIK\fR
or
\fIM\fR(1K = 1024, 1M = 1024K). This option does not affect BitTorrent download. Default:
\fI0\fR
.TP 3n
\-\-max\-download\-limit=SPEED
Set max download speed in bytes per sec.
\fI0\fR
means unrestricted. You can append
\fIK\fR
or
\fIM\fR(1K = 1024, 1M = 1024K). Default:
\fI0\fR
.TP 3n
\-\-file\-allocation=METHOD
Specify file allocation method.
\fIMETHOD\fR
is either
\fInone\fR
or
\fIprealloc\fR.
\fInone\fR
doesn't pre\-allocate file space.
\fIprealloc\fR
pre\-allocates file space before download begins. This may take some time depending on the size of file. Default:
\fInone\fR
.TP 3n
\-\-allow\-overwrite=true|false
If this option set to
\fIfalse\fR, aria2 doesn't download a file which already exists in the file system but its corresponding .aria2 file doesn't exist. Default:
\fIfalse\fR
.TP 3n
\-\-check\-integiry=true|false
Check file integiry by validating piece hash. This option makes effect in BitTorrent download and Metalink with chunk checksums. Use this option to redownload a damaged portion of file. You may need to specify
\fI\-\-allow\-overwrite=true\fR
option if .aria2 file doesn't exist. Default:
\fIfalse\fR
.TP 3n
\-\-realtime\-chunk\-checksum=true|false
Validate chunk checksum while downloading a file in Metalink mode. This option makes effect in Metalink with chunk checksums. Default:
\fItrue\fR
.TP 3n
\-T, \-\-torrent\-file=TORRENT_FILE
The file path to .torrent file.
.TP 3n
\-\-follow\-torrent=true|false
Setting this option to
\fIfalse\fR
prevents aria2 to enter BitTorrent mode even if the filename of downloaded file ends with .torrent. Default:
\fItrue\fR
.TP 3n
\-S, \-\-show\-files
Print file listing of .torrent file and exit.
.TP 3n
\-\-direct\-file\-mapping=true|false
Directly read from and write to each file mentioned in .torrent file. Default:
\fItrue\fR
.TP 3n
\-\-listen\-port=PORT
Set port number to listen to for peer connection.
.TP 3n
\-\-max\-upload\-limit=SPEED
Set max upload speed in bytes per sec.
\fI0\fR
means unrestricted. You can append
\fIK\fR
or
\fIM\fR(1K = 1024, 1M = 1024K). Default:
\fI0\fR
.TP 3n
\-\-select\-file=INDEX\&...
Set file to download by specifing its index. You can know file index through
\fI\-\-show\-files\fR
option. Multiple indexes can be specified by using
\fI,\fR
like "3,6". You can also use
\fI\-\fR
to specify rangelike "1\-5".
\fI,\fR
and
\fI\-\fR
can be used together.
.TP 3n
\-\-seed\-time=MINUTES
Specify seeding time in minutes. See also
\fI\-\-seed\-ratio\fR
option.
.TP 3n
\-\-seed\-ratio=RATIO
Specify share ratio. Seed completed torrents until share ratio reaches
\fIRATIO\fR.
\fI1.0\fR
is encouraged. If
\fI\-\-seed\-time\fR
option is specified along with this option, seeding ends when at least one of the conditions is satisfied.
.TP 3n
\-M, \-\-metalink\-file=METALINK_FILE
The file path to .metalink file.
.TP 3n
\-C, \-\-metalink\-servers=NUM_SERVERS
The number of servers to connect to simultaneously. If more than one connection per server is required, use
\fI\-s\fR
option. Default:
\fI15\fR
.TP 3n
\-\-metalink\-version=VERSION
The version of file to download.
.TP 3n
\-\-metalink\-language=LANGUAGE
The language of file to download.
.TP 3n
\-\-metalink\-os=OS
The operating system the file is targeted.
.TP 3n
\-\-metalink\-location=LOCATION
The location of the prefered server.
.TP 3n
\-\-follow\-metalink=true|false
Setting this option to
\fIfalse\fR
prevents aria2 to enter Metalink mode even if the filename of downloaded file ends with .metalink. Default:
\fItrue\fR
.TP 3n
\-v, \-\-version
Print the version number and exit.
.TP 3n
\-h, \-\-help
Print this message and exit.
.TP 3n
URL
You can specify multiple URLs. All URLs must point to the same file or downloading fails.
.TP 3n
FILE
Specify files in multi\-file torrent to download. Use conjunction with
\fI\-T\fR
option. This arguments are ignored if you specify
\fI\-\-select\-file\fR
option.
.SH "EXAMPLES"
.TP 3n
Download a file by 1 connection
aria2c http://AAA.BBB.CCC/file.zip
.TP 3n
Download a file by 2 connections
aria2c \-s 2 http://AAA.BBB.CCC/file.zip
.TP 3n
Download a file by 2 connections, each connects to a different server
aria2c http://AAA.BBB.CCC/file.zip http://DDD.EEE.FFF/GGG/file.zip
.TP 3n
You can mix up different protocols
aria2c http://AAA.BBB.CCC/file.zip ftp://DDD.EEE.FFF/GGG/file.zip
.TP 3n
Download a torrent
aria2c \-o test.torrent http://AAA.BBB.CCC/file.torrent
.TP 3n
Download a torrent using local .torrent file
aria2c \-T test.torrent
.TP 3n
Download only selected files
aria2c \-T test.torrent dir/file1.zip dir/file2.zip
.TP 3n
Print file listing of .torrent file
aria2c \-T test.torrent \-S
.TP 3n
Metalink downloading
aria2c \-\-lowest\-speed\-limit 10K http://AAA.BBB.CCC/file.metalink
.TP 3n
Download a file using local .metalink file
aria2c \-M test.metalink
.TP 3n
Metalink downloading with preferences
aria2c \-M test.metalink \-\-metalink\-version=1.1.1 \-\-metalink\-language=en\-US
.SH "REPORTING BUGS"
Report bugs to Tatsuhiro Tsujikawa <t\-tujikawa@users.sourceforge.net>
.sp
.SH "AUTHOR"
Tatsuhiro Tsujikawa <t\-tujikawa@users.sourceforge.net>
.sp
.SH "COPYRIGHT"
Copyright \(co 2006, 2007 Tatsuhiro Tsujikawa
.sp
