.TH cppunit 1 "September 2001"
.SH NAME
cppunit-config - script to get information about the installed version of cppunit
.SH SYNOPSIS
.B cppunit-config
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.PP
\fIcppunit-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile and link
programs that use \fIcppunit\fP. It is also used internally to the .m4
macros for GNU autoconf that are included with \fIcppunit\fP.
.
.SH OPTIONS
.l
\fIcppunit-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIcppunit\fP on the standard
output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIcppunit\fP
program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIcppunit\fP
program.
.TP 8
.B  \-\-prefix
Print the prefix with which \fIcppunit\fP was compiled.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that
\fIcppunit\fP was built with when computing the output for the
\-\-cflags and \-\-libs options. This option is also used for the exec
prefix if \-\-exec\-prefix was not specified. This option must be
specified before any \-\-libs or \-\-cflags options.
.TP 8
.B  \-\-exec\-prefix
Print the exec\-prefix with which \fIcppunit\fP was compiled.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that
\fIcppunit\fP was built with when computing the output for the
\-\-cflags and \-\-libs options.  This option must be specified before
any \-\-libs or \-\-cflags options.
.SH COPYRIGHT
cppunit Copyright \(co 1996-2000 by Michael Feathers <mfeathers@objectmentor.com>  
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.SH AUTHOR
This manpage is an almost word-for-word copy of the gtk-config
manpage, written by Owen Taylor.  It was modified by E. Sommerlade
<eric@sommerla.de>.
