#!/bin/tcsh
###########################################################################
# FILE:    make_lib
# PURPOSE: Create Makefile from project file and then make QtTestRunner
#          library.
###########################################################################

qmake qttestrunnerlib.pro
make distclean
make
