name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: autoreconf
      run: autoreconf -i
      
    - name: configure with binary
      run: ./configure ARIA2_STATIC=yes

    - name: Install dependencies
      run: make
    
    - name: aria2 binary upload
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        #name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./src/aria2c
        # The desired behavior if no files are found using the provided path.
